// <auto-generated />
namespace projeto_final_dm106_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Authentication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Authentication));
        
        string IMigrationMetadata.Id
        {
            get { return "201708131422187_Authentication"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
